# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seats_reserved",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of seats booked",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Seats Reserved",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for all seats",
                        max_digits=10,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="External payment system reference",
                        max_length=255,
                        verbose_name="Payment Reference",
                    ),
                ),
                (
                    "pickup_note",
                    models.TextField(
                        blank=True,
                        help_text="Additional info for pickup location",
                        max_length=500,
                        verbose_name="Pickup Note",
                    ),
                ),
                (
                    "passenger_message",
                    models.TextField(
                        blank=True,
                        help_text="Message from passenger to driver",
                        max_length=500,
                        verbose_name="Message to Driver",
                    ),
                ),
                (
                    "driver_message",
                    models.TextField(
                        blank=True,
                        help_text="Message from driver to passenger",
                        max_length=500,
                        verbose_name="Message from Driver",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
