# Generated by Django 5.2.9 on 2025-12-12 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking_request", "New Booking Request"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("booking_rejected", "Booking Rejected"),
                            ("ride_starting", "Ride Starting Soon"),
                            ("ride_started", "Ride Started"),
                            ("ride_cancelled", "Ride Cancelled"),
                            ("ride_completed", "Ride Completed"),
                            ("driver_verified", "Driver Verified"),
                            ("document_approved", "Document Approved"),
                            ("document_rejected", "Document Rejected"),
                            ("new_review", "New Review"),
                            ("system", "System Notification"),
                            ("promotional", "Promotional"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(max_length=1000, verbose_name="Message")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text='Type of related object (e.g., "booking", "ride")',
                        max_length=50,
                        verbose_name="Reference Type",
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related object",
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(default=False, verbose_name="Push Sent"),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Push Sent At"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email Sent"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email Sent At"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or deep link for notification action",
                        max_length=500,
                        verbose_name="Action URL",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification expires and should be auto-deleted",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_booking_updates",
                    models.BooleanField(
                        default=True, verbose_name="Email: Booking Updates"
                    ),
                ),
                (
                    "email_ride_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Email: Ride Reminders"
                    ),
                ),
                (
                    "email_promotional",
                    models.BooleanField(
                        default=False, verbose_name="Email: Promotional"
                    ),
                ),
                (
                    "push_booking_updates",
                    models.BooleanField(
                        default=True, verbose_name="Push: Booking Updates"
                    ),
                ),
                (
                    "push_ride_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Push: Ride Reminders"
                    ),
                ),
                (
                    "push_chat_messages",
                    models.BooleanField(
                        default=True, verbose_name="Push: Chat Messages"
                    ),
                ),
                (
                    "push_promotional",
                    models.BooleanField(
                        default=False, verbose_name="Push: Promotional"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
    ]
