# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(db_index=True, verbose_name="Departure Time"),
                ),
                (
                    "seats_total",
                    models.PositiveIntegerField(
                        help_text="Total number of seats available for passengers",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Total Seats",
                    ),
                ),
                (
                    "seats_available",
                    models.PositiveIntegerField(
                        help_text="Number of seats currently available",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Available Seats",
                    ),
                ),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic point for pickup location",
                        srid=4326,
                        verbose_name="Start Location",
                    ),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic point for dropoff location",
                        srid=4326,
                        verbose_name="End Location",
                    ),
                ),
                (
                    "start_city",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Start City"
                    ),
                ),
                (
                    "start_address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Start Address"
                    ),
                ),
                (
                    "end_city",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="End City"
                    ),
                ),
                (
                    "end_address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="End Address"
                    ),
                ),
                (
                    "price_per_seat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in EUR for one seat",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price per Seat",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "estimated_distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Estimated Distance (km)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the ride",
                        max_length=1000,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "allows_detours",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the driver can make small detours for pickups",
                        verbose_name="Allows Detours",
                    ),
                ),
                (
                    "instant_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Allow passengers to book without driver approval",
                        verbose_name="Instant Booking",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride",
                "verbose_name_plural": "Rides",
                "db_table": "rides",
                "ordering": ["-departure_time"],
            },
        ),
        migrations.CreateModel(
            name="RideRecurring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "Monday"),
                                (1, "Tuesday"),
                                (2, "Wednesday"),
                                (3, "Thursday"),
                                (4, "Friday"),
                                (5, "Saturday"),
                                (6, "Sunday"),
                            ]
                        ),
                        help_text="Days when this recurring ride is active (0=Monday, 6=Sunday)",
                        size=None,
                        verbose_name="Days of Week",
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        help_text="Departure time", verbose_name="Time of Day"
                    ),
                ),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Start Location"
                    ),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="End Location"
                    ),
                ),
                (
                    "start_city",
                    models.CharField(max_length=255, verbose_name="Start City"),
                ),
                (
                    "start_address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Start Address"
                    ),
                ),
                ("end_city", models.CharField(max_length=255, verbose_name="End City")),
                (
                    "end_address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="End Address"
                    ),
                ),
                (
                    "seats_total",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Total Seats",
                    ),
                ),
                (
                    "price_per_seat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price per Seat",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Start date for generating rides",
                        verbose_name="Valid From",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="End date for generating rides (null = indefinite)",
                        null=True,
                        verbose_name="Valid Until",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rides",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_rides",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Ride",
                "verbose_name_plural": "Recurring Rides",
                "db_table": "ride_recurring",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RideStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Stop Name")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Location"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Address"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of the stop in the route (1 = first stop)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "estimated_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated Arrival"
                    ),
                ),
                (
                    "price_from_start",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per seat from ride start to this stop",
                        max_digits=10,
                        null=True,
                        verbose_name="Price from Start",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="rides.ride",
                        verbose_name="Ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Stop",
                "verbose_name_plural": "Ride Stops",
                "db_table": "ride_stops",
                "ordering": ["ride", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["departure_time"], name="rides_departu_80b9cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["status"], name="rides_status_376a74_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["start_city", "end_city"], name="rides_start_c_24a157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["driver"], name="rides_driver__8fdcf2_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["seats_available"], name="rides_seats_a_8ca3a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["price_per_seat"], name="rides_price_p_9a942a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ridestop",
            unique_together={("ride", "order")},
        ),
    ]
