# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Driver's license number",
                        max_length=50,
                        unique=True,
                        verbose_name="License Number",
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="License Expiry Date"
                    ),
                ),
                (
                    "license_photo_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="License Photo URL",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        help_text="Average rating from 0 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "total_trips",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of completed trips",
                        verbose_name="Total Trips",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of reviews received",
                        verbose_name="Total Reviews",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the driver has been verified by admin",
                        verbose_name="Verified Driver",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the driver is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short description about the driver",
                        max_length=500,
                        verbose_name="Bio",
                    ),
                ),
                (
                    "accepts_smoking",
                    models.BooleanField(default=False, verbose_name="Accepts Smoking"),
                ),
                (
                    "accepts_pets",
                    models.BooleanField(default=False, verbose_name="Accepts Pets"),
                ),
                (
                    "accepts_luggage",
                    models.BooleanField(default=True, verbose_name="Accepts Luggage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "db_table": "drivers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("license", "Driver License"),
                            ("insurance", "Insurance"),
                            ("registration", "Vehicle Registration"),
                            ("id_card", "ID Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(max_length=500, verbose_name="Document URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Driver Document",
                "verbose_name_plural": "Driver Documents",
                "db_table": "driver_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
