# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="drivers.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["license_number"], name="drivers_license_29348f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["rating"], name="drivers_rating_884ca4_idx"),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["is_verified", "is_active"], name="drivers_is_veri_680c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["created_at"], name="drivers_created_89688b_idx"
            ),
        ),
    ]
