# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Vehicle manufacturer (e.g., Toyota, BMW)",
                        max_length=100,
                        verbose_name="Make",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Vehicle model (e.g., Corolla, 3 Series)",
                        max_length=100,
                        verbose_name="Model",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Manufacturing year",
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Year",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="License Plate",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("silver", "Silver"),
                            ("gray", "Gray"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("brown", "Brown"),
                            ("orange", "Orange"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Number of passenger seats available (excluding driver)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Available Seats",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Photo URL"
                    ),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(default=True, verbose_name="Air Conditioning"),
                ),
                ("has_wifi", models.BooleanField(default=False, verbose_name="WiFi")),
                (
                    "has_usb_charger",
                    models.BooleanField(default=False, verbose_name="USB Charger"),
                ),
                (
                    "trunk_space",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Trunk Space",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the vehicle is currently available for rides",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the vehicle has been verified by admin",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["license_plate"], name="vehicles_license_b08e3c_idx"
                    ),
                    models.Index(fields=["driver"], name="vehicles_driver__f9fb09_idx"),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="vehicles_is_acti_49391b_idx",
                    ),
                    models.Index(
                        fields=["make", "model"], name="vehicles_make_17021f_idx"
                    ),
                ],
            },
        ),
    ]
