# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("driver", "Driver Review"),
                            ("passenger", "Passenger Review"),
                        ],
                        max_length=20,
                        verbose_name="Review Type",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Comment"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Response from the reviewed user",
                        max_length=500,
                        verbose_name="Response",
                    ),
                ),
                (
                    "response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response At"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the review is publicly visible",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the review has been flagged for moderation",
                        verbose_name="Flagged",
                    ),
                ),
                (
                    "flagged_reason",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Flagged Reason"
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Moderated At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
