# Generated by Django 5.2.9 on 2025-12-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Moderated By",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="rides.ride",
                verbose_name="Ride",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target User",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["ride"], name="reviews_ride_id_2e9228_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["reviewer"], name="reviews_reviewe_965d53_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["target"], name="reviews_target__20af50_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rating_17e8a4_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="reviews_created_53b5d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("ride", "reviewer", "target"),
                name="unique_review_per_ride_reviewer_target",
            ),
        ),
    ]
